get 'projects/:project_id/calendar_subscription', :to => 'calendar_subscription#show', :as => 'project_calendar_subscription'
get 'calendar_subscription', :to => 'calendar_subscription#show'
get 'calendar_subscription/admin/users', :to => 'calendar_subscription_admin#users'
get 'calendar_subscription/admin/credentials', :to => 'calendar_subscription_admin#credentials_index'
post 'calendar_subscription/admin/credentials', :to => 'calendar_subscription_admin#upsert_credential'
delete 'calendar_subscription/admin/credentials/:user_id', :to => 'calendar_subscription_admin#destroy_credential', :as => 'calendar_subscription_admin_credential'
get 'calendar_subscription/admin', :to => 'calendar_subscription_admin#index'
get 'calendar_subscription/admin/allowed', :to => 'calendar_subscription_admin#allowed_index'
post 'calendar_subscription/admin/allowed', :to => 'calendar_subscription_admin#allowed_add'
delete 'calendar_subscription/admin/allowed/:user_id', :to => 'calendar_subscription_admin#allowed_remove'
get 'calendar_subscription/admin/user/:user_id', :to => 'calendar_subscription_admin#user_details'
